In [2]:
import polars as pl

## List of stops

In [3]:
stops = pl.scan_csv("../../ressources/stops.txt")
stops.collect()

shape: (53_543, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ stop_id   ┆ stop_code ┆ stop_name ┆ stop_desc ┆ … ┆ level_id ┆ wheelchai ┆ platform_ ┆ stop_acce │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---      ┆ r_boardin ┆ code      ┆ ss        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str      ┆ g         ┆ ---       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆           ┆   ┆          ┆ i64       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ IDFM:mono ┆ null      ┆ Nation    ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:473 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 875       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Chatou -  ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ Croissy   ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:537 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 83        ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Le        ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ Vésinet - ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:537 ┆           ┆ Centre    ┆           ┆   ┆          ┆           ┆           ┆           │
│ 84        ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Denfert-R ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ ochereau  ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:473 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 890       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Cité Univ ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ ersitaire ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:473 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 843       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ IDFM:Stop ┆ 2         ┆ rte de    ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆ Limours   ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5021 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 117…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:Stop ┆ 2         ┆ av. de    ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆ Madrid    ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5021 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 118…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:Stop ┆ 1         ┆ r. du     ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆ Château   ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5021 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 118…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:Stop ┆ 1         ┆ Entrée /  ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆ Sortie    ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5021 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 117…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:Stop ┆ null      ┆ Lognes    ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5017 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 030…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [23]:
stops.filter(pl.col("stop_id") == "IDFM:monomodalStopPlace:411440").collect()

shape: (1, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ stop_id   ┆ stop_code ┆ stop_name ┆ stop_desc ┆ … ┆ level_id ┆ wheelchai ┆ platform_ ┆ stop_acce │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---      ┆ r_boardin ┆ code      ┆ ss        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str      ┆ g         ┆ ---       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆           ┆   ┆          ┆ i64       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ IDFM:mono ┆ null      ┆ Creil     ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ modalStop ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:411 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 440       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [5]:
stops.filter(pl.col("stop_name").str.ends_with("Les Halles")).select("stop_id", "stop_name", "parent_station").collect()

shape: (5, 3)
┌───────────────────────────────┬───────────────────────┬────────────────┐
│ stop_id                       ┆ stop_name             ┆ parent_station │
│ ---                           ┆ ---                   ┆ ---            │
│ str                           ┆ str                   ┆ str            │
╞═══════════════════════════════╪═══════════════════════╪════════════════╡
│ IDFM:monomodalStopPlace:45102 ┆ Châtelet - Les Halles ┆ IDFM:474151    │
│ IDFM:22146                    ┆ Les Halles            ┆ IDFM:73794     │
│ IDFM:463208                   ┆ Les Halles            ┆ IDFM:73794     │
│ IDFM:73794                    ┆ Les Halles            ┆ null           │
│ IDFM:474151                   ┆ Châtelet - Les Halles ┆ null           │
└───────────────────────────────┴───────────────────────┴────────────────┘

## Parents stations

In [6]:
parent_stops = (
    stops.lazy()
    .filter(pl.col("parent_station").is_null())
)
parent_stops.collect()

shape: (15_393, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ stop_id   ┆ stop_code ┆ stop_name ┆ stop_desc ┆ … ┆ level_id ┆ wheelchai ┆ platform_ ┆ stop_acce │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---      ┆ r_boardin ┆ code      ┆ ss        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str      ┆ g         ┆ ---       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆           ┆   ┆          ┆ i64       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ IDFM:4926 ┆ null      ┆ Rue de    ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 31        ┆           ┆ Paris     ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:4934 ┆ null      ┆ Place du  ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 89        ┆           ┆ Général   ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ Catroux   ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:4967 ┆ null      ┆ Domaine   ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 92        ┆           ┆ Saint     ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ Georges   ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:4949 ┆ null      ┆ Boulevard ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 74        ┆           ┆ de Soave  ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:4949 ┆ null      ┆ Maison de ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 73        ┆           ┆ Santé     ┆           ┆   ┆          ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ IDFM:4115 ┆ null      ┆ Chartres  ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 08        ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:4115 ┆ null      ┆ Saint-Pia ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 02        ┆           ┆ t         ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:4115 ┆ null      ┆ Épernon   ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 12        ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:7434 ┆ null      ┆ Maintenon ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 9         ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:4911 ┆ null      ┆ Lavillete ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 64        ┆           ┆ rtre      ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

## Child stations

In [7]:
child_stops = (
    stops.lazy()
    .filter(pl.col("parent_station").is_not_null())
)
child_stops.collect()

shape: (38_150, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ stop_id   ┆ stop_code ┆ stop_name ┆ stop_desc ┆ … ┆ level_id ┆ wheelchai ┆ platform_ ┆ stop_acce │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---      ┆ r_boardin ┆ code      ┆ ss        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str      ┆ g         ┆ ---       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆           ┆   ┆          ┆ i64       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ IDFM:mono ┆ null      ┆ Nation    ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:473 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 875       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Chatou -  ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ Croissy   ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:537 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 83        ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Le        ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ Vésinet - ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:537 ┆           ┆ Centre    ┆           ┆   ┆          ┆           ┆           ┆           │
│ 84        ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Denfert-R ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ ochereau  ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:473 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 890       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Cité Univ ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ ersitaire ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:473 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 843       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ IDFM:Stop ┆ 2         ┆ rte de    ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆ Limours   ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5021 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 117…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:Stop ┆ 2         ┆ av. de    ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆ Madrid    ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5021 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 118…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:Stop ┆ 1         ┆ r. du     ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆ Château   ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5021 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 118…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:Stop ┆ 1         ┆ Entrée /  ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆ Sortie    ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5021 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 117…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:Stop ┆ null      ┆ Lognes    ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5017 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 030…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

## Parent station with all child stations

In [8]:
parent_child_stops = (
    parent_stops.lazy()
    .select(["stop_id", "stop_name"])
    .join(
        child_stops.lazy(),
        left_on="stop_id",
        right_on="parent_station",
        how="left")
    .group_by(["stop_id", "stop_name"])
    .agg(pl.col("stop_id_right").alias("child_stations"),
         pl.col("stop_name_right").alias("child_stations_names")
    )
)
parent_child_stops.collect()

shape: (15_393, 4)
┌────────────┬───────────────────────┬──────────────────────────────┬──────────────────────────────┐
│ stop_id    ┆ stop_name             ┆ child_stations               ┆ child_stations_names         │
│ ---        ┆ ---                   ┆ ---                          ┆ ---                          │
│ str        ┆ str                   ┆ list[str]                    ┆ list[str]                    │
╞════════════╪═══════════════════════╪══════════════════════════════╪══════════════════════════════╡
│ IDFM:60937 ┆ Église                ┆ ["IDFM:4785", "IDFM:4784"]   ┆ ["Église", "Église"]         │
│ IDFM:67119 ┆ Collège Les Coutures  ┆ ["IDFM:29695", "IDFM:29705"] ┆ ["Collège Les Coutures",     │
│            ┆                       ┆                              ┆ "Coll…                       │
│ IDFM:68893 ┆ Pierris / Saint Jean  ┆ ["IDFM:11244", "IDFM:4940"]  ┆ ["Saint Jean Bosco",         │
│            ┆ Bosco                 ┆                              ┆ "Pierris"…                   │
│ IDFM:64825 ┆ Lavoisier             ┆ ["IDFM:7626", "IDFM:7627"]   ┆ ["Lavoisier", "Lavoisier"]   │
│ IDFM:70667 ┆ Marcel Duchamp        ┆ ["IDFM:25333"]               ┆ ["Marcel Duchamp"]           │
│ …          ┆ …                     ┆ …                            ┆ …                            │
│ IDFM:68642 ┆ Molveaux              ┆ ["IDFM:10577", "IDFM:10578"] ┆ ["Molveaux", "Molveaux"]     │
│ IDFM:72652 ┆ Drancy                ┆ ["IDFM:monomodalStopPlace:43 ┆ ["Drancy", "Gare de Drancy", │
│            ┆                       ┆ 12…                          ┆ ……                           │
│ IDFM:72636 ┆ Edouard Vaillant      ┆ ["IDFM:27656", "IDFM:27655"] ┆ ["Edouard Vaillant",         │
│            ┆                       ┆                              ┆ "Edouard …                   │
│ IDFM:64470 ┆ Saint Laurent         ┆ ["IDFM:17431", "IDFM:17531"] ┆ ["Saint Laurent", "Saint     │
│            ┆                       ┆                              ┆ Laure…                       │
│ IDFM:72209 ┆ Prague                ┆ ["IDFM:23770", "IDFM:8052"]  ┆ ["Prague", "Prague"]         │
└────────────┴───────────────────────┴──────────────────────────────┴──────────────────────────────┘

## RER - metro routes

In [9]:
routes = pl.scan_csv("../../ressources/routes.txt")

rer_metro_routes = (
    routes.lazy()
    .filter(pl.col("route_type").is_in([1, 2]))
    .sort("route_short_name")
)
rer_metro_routes.collect()

shape: (40, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ route_id  ┆ agency_id ┆ route_sho ┆ route_lon ┆ … ┆ route_url ┆ route_col ┆ route_tex ┆ route_so │
│ ---       ┆ ---       ┆ rt_name   ┆ g_name    ┆   ┆ ---       ┆ or        ┆ t_color   ┆ rt_order │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ IDFM:C013 ┆ IDFM:Oper ┆ 1         ┆ 1         ┆ … ┆ null      ┆ FFBE00    ┆ 000000    ┆ null     │
│ 71        ┆ ator_100  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C013 ┆ IDFM:Oper ┆ 10        ┆ 10        ┆ … ┆ null      ┆ DC9600    ┆ 000000    ┆ null     │
│ 80        ┆ ator_100  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C013 ┆ IDFM:Oper ┆ 11        ┆ 11        ┆ … ┆ null      ┆ 6E491E    ┆ FFFFFF    ┆ null     │
│ 81        ┆ ator_100  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C013 ┆ IDFM:Oper ┆ 12        ┆ 12        ┆ … ┆ null      ┆ 00643C    ┆ FFFFFF    ┆ null     │
│ 82        ┆ ator_100  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C013 ┆ IDFM:Oper ┆ 13        ┆ 13        ┆ … ┆ null      ┆ 82C8E6    ┆ 000000    ┆ null     │
│ 83        ┆ ator_100  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ IDFM:C023 ┆ IDFM:93   ┆ TER       ┆ TER       ┆ … ┆ null      ┆ AAAAAA    ┆ 000000    ┆ null     │
│ 68        ┆           ┆           ┆ Centre -  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Val de    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Loire     ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C023 ┆ IDFM:93   ┆ TER       ┆ TER       ┆ … ┆ null      ┆ AAAAAA    ┆ 000000    ┆ null     │
│ 70        ┆           ┆           ┆ Normandie ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C023 ┆ IDFM:93   ┆ TER       ┆ TER       ┆ … ┆ null      ┆ AAAAAA    ┆ 000000    ┆ null     │
│ 75        ┆           ┆           ┆ Normandie ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C017 ┆ IDFM:1046 ┆ U         ┆ U         ┆ … ┆ null      ┆ B6134C    ┆ FFFFFF    ┆ null     │
│ 41        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C027 ┆ IDFM:1046 ┆ V         ┆ V         ┆ … ┆ null      ┆ 9F9825    ┆ FFFFFF    ┆ null     │
│ 11        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Trips

In [10]:
trips = pl.scan_csv("../../ressources/trips.txt")
trips.collect()

shape: (639_940, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ route_id  ┆ service_i ┆ trip_id   ┆ trip_head ┆ … ┆ block_id ┆ shape_id  ┆ wheelchai ┆ bikes_all │
│ ---       ┆ d         ┆ ---       ┆ sign      ┆   ┆ ---      ┆ ---       ┆ r_accessi ┆ owed      │
│ str       ┆ ---       ┆ str       ┆ ---       ┆   ┆ str      ┆ str       ┆ ble       ┆ ---       │
│           ┆ str       ┆           ┆ str       ┆   ┆          ┆           ┆ ---       ┆ i64       │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ i64       ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ IDFM:C013 ┆ IDFM:1    ┆ IDFM:RATP ┆ Funiculai ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 85        ┆           ┆ :COU_RATP ┆ re Gare   ┆   ┆          ┆ 7_2       ┆           ┆           │
│           ┆           ┆ _388795_3 ┆ basse     ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ 139…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ IDFM:1    ┆ IDFM:RATP ┆ Porte de  ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 74        ┆           ┆ :COU_RATP ┆ l'Essonne ┆   ┆          ┆ 0_274     ┆           ┆           │
│           ┆           ┆ _017DIM01 ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ Dim…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C005 ┆ IDFM:1    ┆ IDFM:stif ┆ Terminal  ┆ … ┆ null     ┆ IDFM:shp_ ┆ 0         ┆ 0         │
│ 62        ┆           ┆ :local-17 ┆ 2 F       ┆   ┆          ┆ 3_8659    ┆           ┆           │
│           ┆           ┆ 5995-C005 ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ 62-…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ IDFM:1    ┆ IDFM:stif ┆ Terminal  ┆ … ┆ null     ┆ IDFM:shp_ ┆ 2         ┆ 0         │
│ 92        ┆           ┆ :local-17 ┆ 2 F       ┆   ┆          ┆ 3_8663    ┆           ┆           │
│           ┆           ┆ 5995-C017 ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ 92-…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C005 ┆ IDFM:1    ┆ IDFM:stif ┆ Terminal  ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 63        ┆           ┆ :local-17 ┆ 2 Gare    ┆   ┆          ┆ 0_256     ┆           ┆           │
│           ┆           ┆ 5995-C005 ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ 63-…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ IDFM:C017 ┆ IDFM:TN:f ┆ IDFM:TN:S ┆ POMA      ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 37        ┆ 168cfc3-7 ┆ NCF:3921e ┆           ┆   ┆          ┆ 2_150     ┆           ┆           │
│           ┆ 066-34ea- ┆ cab-06ef- ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆ a76…      ┆ 4c8…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ IDFM:TN:f ┆ IDFM:TN:S ┆ MONY      ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 29        ┆ 2122509-d ┆ NCF:7072c ┆           ┆   ┆          ┆ 2_419     ┆           ┆           │
│           ┆ d02-3b8d- ┆ 4a2-7f41- ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆ 807…      ┆ 460…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ IDFM:TN:f ┆ IDFM:TN:S ┆ NOCY      ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 29        ┆ 5362a10-7 ┆ NCF:20416 ┆           ┆   ┆          ┆ 2_72      ┆           ┆           │
│           ┆ e35-31c3- ┆ 3c2-2424- ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆ 853…      ┆ 418…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ IDFM:TN:f ┆ IDFM:TN:S ┆ VONY      ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 29        ┆ 86d080d-a ┆ NCF:1217a ┆           ┆   ┆          ┆ 2_420     ┆           ┆           │
│           ┆ 9bd-3929- ┆ bb1-5523- ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆ aa1…      ┆ 46c…      ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ IDFM:TN:f ┆ IDFM:TN:S ┆ PUMA      ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 31        ┆ e84dcff-6 ┆ NCF:2b108 ┆           ┆   ┆          ┆ 2_330     ┆           ┆           │
│           ┆ 374-3b49- ┆ 657-b6c7- ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆ 8f0…      ┆ 429…      ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

## Trips of metro and RER

In [11]:
rer_metro_trips = (
    rer_metro_routes.lazy()
    .select("route_id", "route_long_name")
    .join(trips.lazy(),
          on="route_id",
          how="inner")
    .sort("route_long_name")
)
rer_metro_trips.collect()

shape: (89_472, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ route_id  ┆ route_lon ┆ service_i ┆ trip_id   ┆ … ┆ block_id ┆ shape_id  ┆ wheelchai ┆ bikes_all │
│ ---       ┆ g_name    ┆ d         ┆ ---       ┆   ┆ ---      ┆ ---       ┆ r_accessi ┆ owed      │
│ str       ┆ ---       ┆ ---       ┆ str       ┆   ┆ str      ┆ str       ┆ ble       ┆ ---       │
│           ┆ str       ┆ str       ┆           ┆   ┆          ┆           ┆ ---       ┆ i64       │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ i64       ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ IDFM:C013 ┆ 1         ┆ IDFM:1    ┆ IDFM:RATP ┆ … ┆ null     ┆ IDFM:shp_ ┆ 2         ┆ 0         │
│ 71        ┆           ┆           ┆ :COU_RATP ┆   ┆          ┆ 1_121     ┆           ┆           │
│           ┆           ┆           ┆ _01DIADEL ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ AID…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C013 ┆ 1         ┆ IDFM:1    ┆ IDFM:stif ┆ … ┆ null     ┆ IDFM:shp_ ┆ 2         ┆ 0         │
│ 71        ┆           ┆           ┆ :local-25 ┆   ┆          ┆ 1_48      ┆           ┆           │
│           ┆           ┆           ┆ 7754-C013 ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 71-…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C013 ┆ 1         ┆ IDFM:1000 ┆ IDFM:stif ┆ … ┆ null     ┆ IDFM:shp_ ┆ 2         ┆ 0         │
│ 71        ┆           ┆ 01        ┆ :local-25 ┆   ┆          ┆ 1_210     ┆           ┆           │
│           ┆           ┆           ┆ 7754-C013 ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 71-…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C013 ┆ 1         ┆ IDFM:1000 ┆ IDFM:stif ┆ … ┆ null     ┆ IDFM:shp_ ┆ 2         ┆ 0         │
│ 71        ┆           ┆ 01        ┆ :local-25 ┆   ┆          ┆ 1_210     ┆           ┆           │
│           ┆           ┆           ┆ 7754-C013 ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 71-…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C013 ┆ 1         ┆ IDFM:1000 ┆ IDFM:stif ┆ … ┆ null     ┆ IDFM:shp_ ┆ 2         ┆ 0         │
│ 71        ┆           ┆ 01        ┆ :local-25 ┆   ┆          ┆ 1_210     ┆           ┆           │
│           ┆           ┆           ┆ 7754-C013 ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 71-…      ┆   ┆          ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 11        ┆           ┆ 8135921   ┆ NCF:87573 ┆   ┆          ┆ 2_274     ┆           ┆           │
│           ┆           ┆           ┆ dca-fda3- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 48d…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 11        ┆           ┆ 8135921   ┆ NCF:e0a13 ┆   ┆          ┆ 2_274     ┆           ┆           │
│           ┆           ┆           ┆ 3e4-8a4a- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 4cf…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 11        ┆           ┆ 8135921   ┆ NCF:eff87 ┆   ┆          ┆ 2_274     ┆           ┆           │
│           ┆           ┆           ┆ 74a-e864- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 4c6…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 11        ┆           ┆ 8135921   ┆ NCF:c51e2 ┆   ┆          ┆ 2_510     ┆           ┆           │
│           ┆           ┆           ┆ 44d-abc4- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 426…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 11        ┆           ┆ 8135921   ┆ NCF:4463d ┆   ┆          ┆ 2_510     ┆           ┆           │
│           ┆           ┆           ┆ 70e-a63d- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 40b…      ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

## Exemple for RER D trips

In [12]:
rer_metro_trips.filter(pl.col("route_long_name") == "D").collect()

shape: (4_274, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ route_id  ┆ route_lon ┆ service_i ┆ trip_id   ┆ … ┆ block_id ┆ shape_id  ┆ wheelchai ┆ bikes_all │
│ ---       ┆ g_name    ┆ d         ┆ ---       ┆   ┆ ---      ┆ ---       ┆ r_accessi ┆ owed      │
│ str       ┆ ---       ┆ ---       ┆ str       ┆   ┆ str      ┆ str       ┆ ble       ┆ ---       │
│           ┆ str       ┆ str       ┆           ┆   ┆          ┆           ┆ ---       ┆ i64       │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ i64       ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ IDFM:C017 ┆ D         ┆ IDFM:TN:0 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 28        ┆           ┆ 0061023-a ┆ NCF:52247 ┆   ┆          ┆ 2_258     ┆           ┆           │
│           ┆           ┆ a68-35c0- ┆ 38c-ca26- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ 8ce…      ┆ 44b…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ D         ┆ IDFM:TN:0 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 28        ┆           ┆ 0061023-a ┆ NCF:9049e ┆   ┆          ┆ 2_531     ┆           ┆           │
│           ┆           ┆ a68-35c0- ┆ 5be-a811- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ 8ce…      ┆ 4ae…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ D         ┆ IDFM:TN:0 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 28        ┆           ┆ 0061023-a ┆ NCF:bb01e ┆   ┆          ┆ 2_344     ┆           ┆           │
│           ┆           ┆ a68-35c0- ┆ 7fb-95bb- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ 8ce…      ┆ 442…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ D         ┆ IDFM:TN:0 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 28        ┆           ┆ 0061023-a ┆ NCF:dccce ┆   ┆          ┆ 2_152     ┆           ┆           │
│           ┆           ┆ a68-35c0- ┆ 41e-98f3- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ 8ce…      ┆ 446…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ D         ┆ IDFM:TN:0 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 28        ┆           ┆ 0061023-a ┆ NCF:514b6 ┆   ┆          ┆ 2_338     ┆           ┆           │
│           ┆           ┆ a68-35c0- ┆ d2d-0454- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ 8ce…      ┆ 4d7…      ┆   ┆          ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ IDFM:C017 ┆ D         ┆ IDFM:TN:8 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 28        ┆           ┆ d7c06e0-6 ┆ NCF:4c6bc ┆   ┆          ┆ 2_380     ┆           ┆           │
│           ┆           ┆ 66e-3f8b- ┆ 351-e440- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ a10…      ┆ 442…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ D         ┆ IDFM:TN:9 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 28        ┆           ┆ 1142439-e ┆ NCF:b550a ┆   ┆          ┆ 2_145     ┆           ┆           │
│           ┆           ┆ 3b6-3571- ┆ 151-e41c- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ be7…      ┆ 418…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ D         ┆ IDFM:TN:e ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 28        ┆           ┆ 31aef55-7 ┆ NCF:b42e2 ┆   ┆          ┆ 2_222     ┆           ┆           │
│           ┆           ┆ 0b0-3dec- ┆ 89f-8432- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ bcb…      ┆ 49a…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ D         ┆ IDFM:TN:e ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 28        ┆           ┆ 31aef55-7 ┆ NCF:45a96 ┆   ┆          ┆ 2_222     ┆           ┆           │
│           ┆           ┆ 0b0-3dec- ┆ 675-85ce- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ bcb…      ┆ 4b1…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ D         ┆ IDFM:TN:e ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 28        ┆           ┆ 31aef55-7 ┆ NCF:f231c ┆   ┆          ┆ 2_160     ┆           ┆           │
│           ┆           ┆ 0b0-3dec- ┆ 67c-2f1c- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ bcb…      ┆ 4ba…      ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

stoptimes

In [13]:
stop_times = pl.scan_csv("../../ressources/stop_times.txt")
stop_times.collect()

shape: (14_176_787, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ trip_id   ┆ arrival_t ┆ departure ┆ start_pic ┆ … ┆ stop_head ┆ timepoint ┆ pickup_bo ┆ drop_off │
│ ---       ┆ ime       ┆ _time     ┆ kup_drop_ ┆   ┆ sign      ┆ ---       ┆ oking_rul ┆ _booking │
│ str       ┆ ---       ┆ ---       ┆ off_windo ┆   ┆ ---       ┆ i64       ┆ e_id      ┆ _rule_id │
│           ┆ str       ┆ str       ┆ w         ┆   ┆ str       ┆           ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ ---       ┆   ┆           ┆           ┆ str       ┆ str      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ IDFM:RATP ┆ 16:46:00  ┆ 16:46:00  ┆ null      ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ :COU_RATP ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _388795_3 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 139…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:RATP ┆ 16:51:00  ┆ 16:51:00  ┆ null      ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ :COU_RATP ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _388795_3 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 139…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:RATP ┆ 23:30:00  ┆ 23:30:00  ┆ null      ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ :COU_RATP ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _017DIM01 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Dim…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:RATP ┆ 23:31:30  ┆ 23:31:30  ┆ null      ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ :COU_RATP ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _017DIM01 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Dim…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:RATP ┆ 23:33:00  ┆ 23:33:00  ┆ null      ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ :COU_RATP ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _017DIM01 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Dim…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ IDFM:TN:S ┆ 05:22:10  ┆ 05:23:10  ┆ null      ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:2b108 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 657-b6c7- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 429…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ 05:28:40  ┆ 05:29:40  ┆ null      ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:2b108 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 657-b6c7- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 429…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ 05:35:10  ┆ 05:36:10  ┆ null      ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:2b108 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 657-b6c7- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 429…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ 05:43:40  ┆ 05:44:40  ┆ null      ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:2b108 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 657-b6c7- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 429…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ 06:13:00  ┆ 06:13:00  ┆ null      ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:2b108 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 657-b6c7- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 429…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Trips stop times

In [14]:
# trip rer A

rer_metro_trips_stop_times = (
    rer_metro_trips.lazy()
    .select(["trip_id", "route_id", "route_long_name", "service_id"])
    .join(stop_times.lazy(),
          on="trip_id",
          how="inner")
    .sort("route_long_name")
)
rer_metro_trips_stop_times.collect()

shape: (1_862_741, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ trip_id   ┆ route_id  ┆ route_lon ┆ service_i ┆ … ┆ stop_head ┆ timepoint ┆ pickup_bo ┆ drop_off │
│ ---       ┆ ---       ┆ g_name    ┆ d         ┆   ┆ sign      ┆ ---       ┆ oking_rul ┆ _booking │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ i64       ┆ e_id      ┆ _rule_id │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆           ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ IDFM:RATP ┆ IDFM:C013 ┆ 1         ┆ IDFM:1    ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ :COU_RATP ┆ 71        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _01DIADEL ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ AID…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:RATP ┆ IDFM:C013 ┆ 1         ┆ IDFM:1    ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ :COU_RATP ┆ 71        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _01DIADEL ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ AID…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:RATP ┆ IDFM:C013 ┆ 1         ┆ IDFM:1    ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ :COU_RATP ┆ 71        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _01DIADEL ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ AID…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:RATP ┆ IDFM:C013 ┆ 1         ┆ IDFM:1    ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ :COU_RATP ┆ 71        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _01DIADEL ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ AID…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:RATP ┆ IDFM:C013 ┆ 1         ┆ IDFM:1    ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ :COU_RATP ┆ 71        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _01DIADEL ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ AID…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ IDFM:TN:S ┆ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:4463d ┆ 11        ┆           ┆ 8135921   ┆   ┆           ┆           ┆           ┆          │
│ 70e-a63d- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 40b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:4463d ┆ 11        ┆           ┆ 8135921   ┆   ┆           ┆           ┆           ┆          │
│ 70e-a63d- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 40b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:4463d ┆ 11        ┆           ┆ 8135921   ┆   ┆           ┆           ┆           ┆          │
│ 70e-a63d- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 40b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:4463d ┆ 11        ┆           ┆ 8135921   ┆   ┆           ┆           ┆           ┆          │
│ 70e-a63d- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 40b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:4463d ┆ 11        ┆           ┆ 8135921   ┆   ┆           ┆           ┆           ┆          │
│ 70e-a63d- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 40b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
def gtfs_time_to_pl(col: str) -> pl.Expr:
    return pl.time(
        hour=pl.col(col).str.extract(r"^(\d+):\d{2}:\d{2}$", 1).cast(pl.Int64) % 24,
        minute=pl.col(col).str.extract(r"^\d+:(\d{2}):\d{2}$", 1).cast(pl.Int64),
        second=pl.col(col).str.extract(r"^\d+:\d{2}:(\d{2})$", 1).cast(pl.Int64),
    ).alias(col)

rer_metro_trips_stop_times = (
    rer_metro_trips_stop_times
    .with_columns(
        gtfs_time_to_pl("departure_time"),
        gtfs_time_to_pl("arrival_time"),
    )
)
rer_metro_trips_stop_times.collect()

shape: (1_862_741, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ trip_id   ┆ route_id  ┆ route_lon ┆ service_i ┆ … ┆ stop_head ┆ timepoint ┆ pickup_bo ┆ drop_off │
│ ---       ┆ ---       ┆ g_name    ┆ d         ┆   ┆ sign      ┆ ---       ┆ oking_rul ┆ _booking │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ i64       ┆ e_id      ┆ _rule_id │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆           ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ IDFM:RATP ┆ IDFM:C013 ┆ 1         ┆ IDFM:1    ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ :COU_RATP ┆ 71        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _01DIADEL ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ AID…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:RATP ┆ IDFM:C013 ┆ 1         ┆ IDFM:1    ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ :COU_RATP ┆ 71        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _01DIADEL ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ AID…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:RATP ┆ IDFM:C013 ┆ 1         ┆ IDFM:1    ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ :COU_RATP ┆ 71        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _01DIADEL ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ AID…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:RATP ┆ IDFM:C013 ┆ 1         ┆ IDFM:1    ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ :COU_RATP ┆ 71        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _01DIADEL ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ AID…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:RATP ┆ IDFM:C013 ┆ 1         ┆ IDFM:1    ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ :COU_RATP ┆ 71        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _01DIADEL ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ AID…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ IDFM:TN:S ┆ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:4463d ┆ 11        ┆           ┆ 8135921   ┆   ┆           ┆           ┆           ┆          │
│ 70e-a63d- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 40b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:4463d ┆ 11        ┆           ┆ 8135921   ┆   ┆           ┆           ┆           ┆          │
│ 70e-a63d- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 40b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:4463d ┆ 11        ┆           ┆ 8135921   ┆   ┆           ┆           ┆           ┆          │
│ 70e-a63d- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 40b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:4463d ┆ 11        ┆           ┆ 8135921   ┆   ┆           ┆           ┆           ┆          │
│ 70e-a63d- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 40b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:4463d ┆ 11        ┆           ┆ 8135921   ┆   ┆           ┆           ┆           ┆          │
│ 70e-a63d- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 40b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## EXEMPLE LIGNE 1 METRO avec stop name

In [25]:
stops.join(
    rer_metro_trips_stop_times
        .filter(pl.col("route_id")=="IDFM:C01371")
        .select(["trip_id", "service_id", "stop_id", "route_id", "route_long_name" , "arrival_time", "departure_time"]),
    on="stop_id",
    how="inner"
).select(["trip_id", "service_id", "stop_id", "stop_name","route_id", "route_long_name", "arrival_time", "departure_time"]).sort("arrival_time").collect()

shape: (113_325, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ trip_id    ┆ service_id ┆ stop_id    ┆ stop_name ┆ route_id  ┆ route_lon ┆ arrival_t ┆ departure │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ g_name    ┆ ime       ┆ _time     │
│ str        ┆ str        ┆ str        ┆ str       ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆            ┆           ┆           ┆ str       ┆ time      ┆ time      │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ IDFM:RATP: ┆ IDFM:10722 ┆ IDFM:22101 ┆ La        ┆ IDFM:C013 ┆ 1         ┆ 00:00:00  ┆ 00:00:00  │
│ COU_RATP_0 ┆ 8          ┆            ┆ Défense   ┆ 71        ┆           ┆           ┆           │
│ 1DIMASCATE ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ IDFM:stif: ┆ IDFM:10496 ┆ IDFM:46294 ┆ Nation    ┆ IDFM:C013 ┆ 1         ┆ 00:00:04  ┆ 00:00:24  │
│ local-2577 ┆ 3          ┆ 3          ┆           ┆ 71        ┆           ┆           ┆           │
│ 54-C01371- ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ IDFM:RATP: ┆ IDFM:11679 ┆ IDFM:46308 ┆ Hôtel de  ┆ IDFM:C013 ┆ 1         ┆ 00:00:07  ┆ 00:00:29  │
│ COU_RATP_0 ┆ 2          ┆ 0          ┆ Ville     ┆ 71        ┆           ┆           ┆           │
│ 1DISEATTLE ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ IDFM:RATP: ┆ IDFM:10722 ┆ IDFM:22084 ┆ George V  ┆ IDFM:C013 ┆ 1         ┆ 00:00:13  ┆ 00:00:29  │
│ COU_RATP_0 ┆ 8          ┆            ┆           ┆ 71        ┆           ┆           ┆           │
│ 1DIMASCATE ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ IDFM:RATP: ┆ IDFM:11679 ┆ IDFM:46304 ┆ Tuileries ┆ IDFM:C013 ┆ 1         ┆ 00:00:13  ┆ 00:00:29  │
│ COU_RATP_0 ┆ 2          ┆ 1          ┆           ┆ 71        ┆           ┆           ┆           │
│ 1DISEATTLE ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ IDFM:RATP: ┆ IDFM:11679 ┆ IDFM:22084 ┆ George V  ┆ IDFM:C013 ┆ 1         ┆ 23:59:43  ┆ 23:59:59  │
│ COU_RATP_0 ┆ 2          ┆            ┆           ┆ 71        ┆           ┆           ┆           │
│ 1DIADELAID ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ IDFM:RATP: ┆ IDFM:10722 ┆ IDFM:22105 ┆ Bérault   ┆ IDFM:C013 ┆ 1         ┆ 23:59:44  ┆ 00:00:02  │
│ COU_RATP_0 ┆ 8          ┆            ┆           ┆ 71        ┆           ┆           ┆           │
│ 1DIMASCATE ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ IDFM:RATP: ┆ IDFM:10722 ┆ IDFM:22080 ┆ Nation    ┆ IDFM:C013 ┆ 1         ┆ 23:59:44  ┆ 00:00:10  │
│ COU_RATP_0 ┆ 8          ┆            ┆           ┆ 71        ┆           ┆           ┆           │
│ 1DIADELAID ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ IDFM:stif: ┆ IDFM:11703 ┆ IDFM:46318 ┆ George V  ┆ IDFM:C013 ┆ 1         ┆ 23:59:51  ┆ 00:00:10  │
│ local-2577 ┆ 1          ┆ 5          ┆           ┆ 71        ┆           ┆           ┆           │
│ 54-C01371- ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ IDFM:stif: ┆ IDFM:10722 ┆ IDFM:46301 ┆ Charles   ┆ IDFM:C013 ┆ 1         ┆ 23:59:52  ┆ 00:00:19  │
│ local-2577 ┆ 8          ┆ 3          ┆ de Gaulle ┆ 71        ┆           ┆           ┆           │
│ 54-C01371- ┆            ┆            ┆ - Étoile  ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

## RER Route by Parent_stop

In [19]:
rer_metro_trips_stops = (
    rer_metro_trips_stop_times.lazy()
    .group_by(["trip_id", "route_id", "route_long_name", "service_id"])
    .agg(pl.col("stop_id")
         .alias("stops"))
)
rer_metro_trips_stops.collect()

shape: (89_472, 5)
┌───────────────────────┬─────────────┬─────────────────┬──────────────────┬───────────────────────┐
│ trip_id               ┆ route_id    ┆ route_long_name ┆ service_id       ┆ stops                 │
│ ---                   ┆ ---         ┆ ---             ┆ ---              ┆ ---                   │
│ str                   ┆ str         ┆ str             ┆ str              ┆ list[str]             │
╞═══════════════════════╪═════════════╪═════════════════╪══════════════════╪═══════════════════════╡
│ IDFM:RATP:COU_RATP_13 ┆ IDFM:C01383 ┆ 13              ┆ IDFM:10000       ┆ ["IDFM:22237",        │
│ DICARHAIX…            ┆             ┆                 ┆                  ┆ "IDFM:463214", …      │
│ IDFM:RATP:COU_RATP_05 ┆ IDFM:C01375 ┆ 5               ┆ IDFM:100171      ┆ ["IDFM:22015",        │
│ JOJADEITE…            ┆             ┆                 ┆                  ┆ "IDFM:463002", …      │
│ IDFM:RATP:COU_RATP_14 ┆ IDFM:C01384 ┆ 14              ┆ IDFM:133820      ┆ ["IDFM:490774",       │
│ JOFOX02_2…            ┆             ┆                 ┆                  ┆ "IDFM:480290",…       │
│ IDFM:TN:SNCF:21b66bf3 ┆ IDFM:C01743 ┆ B               ┆ IDFM:TN:48165887 ┆ ["IDFM:monomodalStopP │
│ -5f6c-4a9…            ┆             ┆                 ┆                  ┆ lace:4733…            │
│ IDFM:RATP:COU_RATP_05 ┆ IDFM:C01375 ┆ 5               ┆ IDFM:100171      ┆ ["IDFM:22006",        │
│ JORUBIS_2…            ┆             ┆                 ┆                  ┆ "IDFM:463020", …      │
│ …                     ┆ …           ┆ …               ┆ …                ┆ …                     │
│ IDFM:RATP:COU_RATP_13 ┆ IDFM:C01383 ┆ 13              ┆ IDFM:100684      ┆ ["IDFM:22237",        │
│ VEMONTJOU…            ┆             ┆                 ┆                  ┆ "IDFM:463214", …      │
│ IDFM:RATP:COU_RATP_12 ┆ IDFM:C01382 ┆ 12              ┆ IDFM:100780      ┆ ["IDFM:22062",        │
│ DIESTEVE1…            ┆             ┆                 ┆                  ┆ "IDFM:22061", ……      │
│ IDFM:RATP:COU_RATP_03 ┆ IDFM:C01373 ┆ 3               ┆ IDFM:100770      ┆ ["IDFM:22035",        │
│ DIPISSARO…            ┆             ┆                 ┆                  ┆ "IDFM:463119", …      │
│ IDFM:RATP:COU_RATP_08 ┆ IDFM:C01378 ┆ 8               ┆ IDFM:10134       ┆ ["IDFM:463057",       │
│ SAITCO26_…            ┆             ┆                 ┆                  ┆ "IDFM:22213", …       │
│ IDFM:RATP:COU_RATP_04 ┆ IDFM:C01374 ┆ 4               ┆ IDFM:104951      ┆ ["IDFM:463073",       │
│ DIDANXIA3…            ┆             ┆                 ┆                  ┆ "IDFM:22133", …       │
└───────────────────────┴─────────────┴─────────────────┴──────────────────┴───────────────────────┘

In [20]:
parent_stops_routes = (
    rer_metro_trips_stops.lazy()
    .explode("stops", empty_as_null=True)
    .rename({"stops": "stop_id"})
    # Récupérer le parent_station de chaque stop
    .join(
        stops.lazy().select(["stop_id", "parent_station"]),
        on="stop_id",
        how="left"
    )
    # Si pas de parent, utiliser le stop lui-même
    .with_columns(
        pl.coalesce(["parent_station", "stop_id"]).alias("parent_station")
    )
    # Récupérer le nom du parent
    .join(
        stops.lazy().select(["stop_id", "stop_name"]),
        left_on="parent_station",
        right_on="stop_id",
        how="left"
    )
    # Grouper par station parente
    .group_by(["parent_station", "stop_name"])
    .agg(
        pl.col("route_long_name").unique().alias("routes"),
        pl.col("route_id").unique().alias("routes_ids")
    )
    .sort("stop_name")
)

parent_stops_routes.collect()

shape: (770, 4)
┌────────────────┬───────────────────────┬───────────────────┬────────────────────────────────┐
│ parent_station ┆ stop_name             ┆ routes            ┆ routes_ids                     │
│ ---            ┆ ---                   ┆ ---               ┆ ---                            │
│ str            ┆ str                   ┆ list[str]         ┆ list[str]                      │
╞════════════════╪═══════════════════════╪═══════════════════╪════════════════════════════════╡
│ IDFM:71432     ┆ Abbesses              ┆ ["12"]            ┆ ["IDFM:C01382"]                │
│ IDFM:69554     ┆ Ablon                 ┆ ["C"]             ┆ ["IDFM:C01727"]                │
│ IDFM:65190     ┆ Achères Grand Cormier ┆ ["A"]             ┆ ["IDFM:C01742"]                │
│ IDFM:73604     ┆ Achères Ville         ┆ ["A", "L"]        ┆ ["IDFM:C01742", "IDFM:C01740"] │
│ IDFM:72491     ┆ Aimé Césaire          ┆ ["12"]            ┆ ["IDFM:C01382"]                │
│ …              ┆ …                     ┆ …                 ┆ …                              │
│ IDFM:411456    ┆ Étigny - Véron        ┆ ["TER Bourgogne - ┆ ["IDFM:C01745"]                │
│                ┆                       ┆ Franche-Comt…     ┆                                │
│ IDFM:59678     ┆ Étréchy               ┆ ["C"]             ┆ ["IDFM:C01727"]                │
│ IDFM:411366    ┆ Évreux Normandie      ┆ ["TER Normandie"] ┆ ["IDFM:C02375"]                │
│ IDFM:60450     ┆ Évry - Courcouronnes  ┆ ["D"]             ┆ ["IDFM:C01728"]                │
│ IDFM:60522     ┆ Évry - Val de Seine   ┆ ["D"]             ┆ ["IDFM:C01728"]                │
└────────────────┴───────────────────────┴───────────────────┴────────────────────────────────┘

In [21]:
gares = "gare de l'est|gare du nord|châtelet|halles|gare de lyon|austerlitz|lazare"
exp = parent_stops_routes.filter(pl.col("stop_name").str.to_lowercase().str.contains(gares).alias("regex")).select(["parent_station", "stop_name", "routes"]).collect()

In [22]:
exp[["parent_station", "stop_name", "routes"]].rows()

[('IDFM:71264', 'Châtelet', ['14', '4', '7', '1', '11']),
 ('IDFM:474151', 'Châtelet - Les Halles', ['B', 'A', 'D']),
 ('IDFM:71370',
  'Gare Saint-Lazare',
  ['TER Normandie', 'L', '12', '13', '3', '14', 'J']),
 ('IDFM:71135',
  "Gare d'Austerlitz",
  ['5', 'C', '10', 'TER Centre - Val-de-Loire']),
 ('IDFM:73626',
  'Gare de Lyon',
  ['14', 'A', 'R', 'D', '1', 'TER Bourgogne - Franche-Comté']),
 ('IDFM:71359', "Gare de l'Est", ['5', '4', 'P', '7', 'TER Grand-Est']),
 ('IDFM:71410',
  'Gare du Nord',
  ['5', 'B', '4', 'H', 'TER Hauts-de-France', 'D', 'K']),
 ('IDFM:73688', 'Haussmann Saint-Lazare', ['E']),
 ('IDFM:73794', 'Les Halles', ['4'])]