In [1]:
import polars as pl

## List of stops

In [2]:
stops = pl.scan_csv("../ressources/stops.txt")
stops.collect()

shape: (53_543, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ stop_id   ┆ stop_code ┆ stop_name ┆ stop_desc ┆ … ┆ level_id ┆ wheelchai ┆ platform_ ┆ stop_acce │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---      ┆ r_boardin ┆ code      ┆ ss        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str      ┆ g         ┆ ---       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆           ┆   ┆          ┆ i64       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ IDFM:mono ┆ null      ┆ Nation    ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:473 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 875       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Chatou -  ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ Croissy   ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:537 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 83        ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Le        ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ Vésinet - ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:537 ┆           ┆ Centre    ┆           ┆   ┆          ┆           ┆           ┆           │
│ 84        ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Denfert-R ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ ochereau  ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:473 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 890       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Cité Univ ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ ersitaire ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:473 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 843       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ IDFM:Stop ┆ 2         ┆ rte de    ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆ Limours   ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5021 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 117…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:Stop ┆ 2         ┆ av. de    ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆ Madrid    ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5021 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 118…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:Stop ┆ 1         ┆ r. du     ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆ Château   ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5021 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 118…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:Stop ┆ 1         ┆ Entrée /  ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆ Sortie    ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5021 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 117…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:Stop ┆ null      ┆ Lognes    ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5017 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 030…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

## Parents stations

In [3]:
parent_stops = (
    stops.lazy()
    .filter(pl.col("parent_station").is_null())
)
parent_stops.collect()

shape: (15_393, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ stop_id   ┆ stop_code ┆ stop_name ┆ stop_desc ┆ … ┆ level_id ┆ wheelchai ┆ platform_ ┆ stop_acce │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---      ┆ r_boardin ┆ code      ┆ ss        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str      ┆ g         ┆ ---       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆           ┆   ┆          ┆ i64       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ IDFM:4926 ┆ null      ┆ Rue de    ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 31        ┆           ┆ Paris     ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:4934 ┆ null      ┆ Place du  ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 89        ┆           ┆ Général   ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ Catroux   ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:4967 ┆ null      ┆ Domaine   ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 92        ┆           ┆ Saint     ┆           ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆ Georges   ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:4949 ┆ null      ┆ Boulevard ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 74        ┆           ┆ de Soave  ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:4949 ┆ null      ┆ Maison de ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 73        ┆           ┆ Santé     ┆           ┆   ┆          ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ IDFM:4115 ┆ null      ┆ Chartres  ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 08        ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:4115 ┆ null      ┆ Saint-Pia ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 02        ┆           ┆ t         ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:4115 ┆ null      ┆ Épernon   ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 12        ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:7434 ┆ null      ┆ Maintenon ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 9         ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:4911 ┆ null      ┆ Lavillete ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ 64        ┆           ┆ rtre      ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

## Child stations

In [4]:
child_stops = (
    stops.lazy()
    .filter(pl.col("parent_station").is_not_null())
)
child_stops.collect()

shape: (38_150, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ stop_id   ┆ stop_code ┆ stop_name ┆ stop_desc ┆ … ┆ level_id ┆ wheelchai ┆ platform_ ┆ stop_acce │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---      ┆ r_boardin ┆ code      ┆ ss        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str      ┆ g         ┆ ---       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆           ┆           ┆   ┆          ┆ i64       ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ IDFM:mono ┆ null      ┆ Nation    ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:473 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 875       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Chatou -  ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ Croissy   ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:537 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 83        ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Le        ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ Vésinet - ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:537 ┆           ┆ Centre    ┆           ┆   ┆          ┆           ┆           ┆           │
│ 84        ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Denfert-R ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ ochereau  ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:473 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 890       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:mono ┆ null      ┆ Cité Univ ┆ null      ┆ … ┆ null     ┆ 1         ┆ null      ┆ null      │
│ modalStop ┆           ┆ ersitaire ┆           ┆   ┆          ┆           ┆           ┆           │
│ Place:473 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 843       ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ IDFM:Stop ┆ 2         ┆ rte de    ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆ Limours   ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5021 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 117…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:Stop ┆ 2         ┆ av. de    ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆ Madrid    ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5021 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 118…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:Stop ┆ 1         ┆ r. du     ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆ Château   ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5021 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 118…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:Stop ┆ 1         ┆ Entrée /  ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆ Sortie    ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5021 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 117…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ IDFM:Stop ┆ null      ┆ Lognes    ┆ null      ┆ … ┆ null     ┆ 0         ┆ null      ┆ null      │
│ PlaceEntr ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ ance:5017 ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
│ 030…      ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

## Parent station with all child stations

In [5]:
parent_child_stops = (
    parent_stops.lazy()
    .select(["stop_id", "stop_name"])
    .join(
        child_stops.lazy(),
        left_on="stop_id",
        right_on="parent_station",
        how="left")
    .group_by(["stop_id", "stop_name"])
    .agg(pl.col("stop_id_right").alias("child_stations"),
         pl.col("stop_name_right").alias("child_stations_names")
    )
)
parent_child_stops.collect()

shape: (15_393, 4)
┌────────────┬────────────────────────┬────────────────────┬───────────────────────────────────┐
│ stop_id    ┆ stop_name              ┆ child_stations     ┆ child_stations_names              │
│ ---        ┆ ---                    ┆ ---                ┆ ---                               │
│ str        ┆ str                    ┆ list[str]          ┆ list[str]                         │
╞════════════╪════════════════════════╪════════════════════╪═══════════════════════════════════╡
│ IDFM:61013 ┆ Thomas                 ┆ ["IDFM:11327",     ┆ ["Thomas", "Thomas"]              │
│            ┆                        ┆ "IDFM:11326"]      ┆                                   │
│ IDFM:64337 ┆ Rousseau               ┆ ["IDFM:34270",     ┆ ["Rousseau", "Rousseau"]          │
│            ┆                        ┆ "IDFM:34269"]      ┆                                   │
│ IDFM:71000 ┆ Collège Henri Matisse  ┆ ["IDFM:493555"]    ┆ ["Collège Henri Matisse"]         │
│ IDFM:68423 ┆ Pomponne               ┆ ["IDFM:16804",     ┆ ["Pomponne", "Pomponne"]          │
│            ┆                        ┆ "IDFM:16803"]      ┆                                   │
│ IDFM:69456 ┆ Collège Stendhal       ┆ ["IDFM:40500"]     ┆ ["Collège Stendhal"]              │
│ …          ┆ …                      ┆ …                  ┆ …                                 │
│ IDFM:62114 ┆ Jobert                 ┆ ["IDFM:427286",    ┆ ["Jobert", "Jobert"]              │
│            ┆                        ┆ "IDFM:31085"]      ┆                                   │
│ IDFM:71141 ┆ Chardon Lagache        ┆ ["IDFM:22791",     ┆ ["Chardon Lagache - Molitor", …   │
│            ┆                        ┆ "IDFM:21985", "…   ┆                                   │
│ IDFM:71575 ┆ Charenton - Jardiniers ┆ ["IDFM:490480"]    ┆ ["Charenton - Jardiniers"]        │
│ IDFM:66272 ┆ Fragonard              ┆ ["IDFM:17887",     ┆ ["Fragonard", "Fragonard"]        │
│            ┆                        ┆ "IDFM:17886"]      ┆                                   │
│ IDFM:66305 ┆ Bel Air - Gosserots    ┆ ["IDFM:28466",     ┆ ["Bel Air - Gosserots", "Bel A…   │
│            ┆                        ┆ "IDFM:30167"]      ┆                                   │
└────────────┴────────────────────────┴────────────────────┴───────────────────────────────────┘

## RER routes

In [6]:
routes = pl.scan_csv("../ressources/routes.txt")

rer_routes = (
    routes.lazy()
    .filter(pl.col("route_type") == 2)
    .sort("route_short_name")
)
rer_routes.collect()

shape: (24, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ route_id  ┆ agency_id ┆ route_sho ┆ route_lon ┆ … ┆ route_url ┆ route_col ┆ route_tex ┆ route_so │
│ ---       ┆ ---       ┆ rt_name   ┆ g_name    ┆   ┆ ---       ┆ or        ┆ t_color   ┆ rt_order │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ IDFM:C017 ┆ IDFM:71   ┆ A         ┆ A         ┆ … ┆ null      ┆ EB2132    ┆ FFFFFF    ┆ null     │
│ 42        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C017 ┆ IDFM:71   ┆ B         ┆ B         ┆ … ┆ null      ┆ 5091CB    ┆ FFFFFF    ┆ null     │
│ 43        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C017 ┆ IDFM:71   ┆ C         ┆ C         ┆ … ┆ null      ┆ FFCC30    ┆ 000000    ┆ null     │
│ 27        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C017 ┆ IDFM:71   ┆ D         ┆ D         ┆ … ┆ null      ┆ 008B5B    ┆ FFFFFF    ┆ null     │
│ 28        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C017 ┆ IDFM:71   ┆ E         ┆ E         ┆ … ┆ null      ┆ B94E9A    ┆ FFFFFF    ┆ null     │
│ 29        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ IDFM:C023 ┆ IDFM:93   ┆ TER       ┆ TER       ┆ … ┆ null      ┆ AAAAAA    ┆ 000000    ┆ null     │
│ 68        ┆           ┆           ┆ Centre -  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Val de    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Loire     ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C023 ┆ IDFM:93   ┆ TER       ┆ TER       ┆ … ┆ null      ┆ AAAAAA    ┆ 000000    ┆ null     │
│ 70        ┆           ┆           ┆ Normandie ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C023 ┆ IDFM:93   ┆ TER       ┆ TER       ┆ … ┆ null      ┆ AAAAAA    ┆ 000000    ┆ null     │
│ 75        ┆           ┆           ┆ Normandie ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C017 ┆ IDFM:1046 ┆ U         ┆ U         ┆ … ┆ null      ┆ B6134C    ┆ FFFFFF    ┆ null     │
│ 41        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:C027 ┆ IDFM:1046 ┆ V         ┆ V         ┆ … ┆ null      ┆ 9F9825    ┆ FFFFFF    ┆ null     │
│ 11        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## RER trips

In [7]:
trips = pl.scan_csv("../ressources/trips.txt")

rer_trips = (
    rer_routes.lazy()
    .select("route_id", "route_long_name")
    .join(trips.lazy(),
          on="route_id",
          how="inner")
    .sort("route_long_name")
)
rer_trips.collect()

shape: (40_853, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ route_id  ┆ route_lon ┆ service_i ┆ trip_id   ┆ … ┆ block_id ┆ shape_id  ┆ wheelchai ┆ bikes_all │
│ ---       ┆ g_name    ┆ d         ┆ ---       ┆   ┆ ---      ┆ ---       ┆ r_accessi ┆ owed      │
│ str       ┆ ---       ┆ ---       ┆ str       ┆   ┆ str      ┆ str       ┆ ble       ┆ ---       │
│           ┆ str       ┆ str       ┆           ┆   ┆          ┆           ┆ ---       ┆ i64       │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ i64       ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ IDFM:C017 ┆ A         ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 42        ┆           ┆ 7973483   ┆ NCF:dee0d ┆   ┆          ┆ 2_54      ┆           ┆           │
│           ┆           ┆           ┆ 87e-8a58- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 4a0…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ A         ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 42        ┆           ┆ 7973483   ┆ NCF:5a1b6 ┆   ┆          ┆ 2_54      ┆           ┆           │
│           ┆           ┆           ┆ 0c5-ad0a- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 41b…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ A         ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 42        ┆           ┆ 7973483   ┆ NCF:f48dc ┆   ┆          ┆ 2_54      ┆           ┆           │
│           ┆           ┆           ┆ 593-b25b- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 4b6…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ A         ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 42        ┆           ┆ 7973483   ┆ NCF:7a18c ┆   ┆          ┆ 2_54      ┆           ┆           │
│           ┆           ┆           ┆ a8f-c7fd- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 45e…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C017 ┆ A         ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 42        ┆           ┆ 7973483   ┆ NCF:85d7d ┆   ┆          ┆ 2_54      ┆           ┆           │
│           ┆           ┆           ┆ 9e9-5e39- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 490…      ┆   ┆          ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 11        ┆           ┆ 8135921   ┆ NCF:87573 ┆   ┆          ┆ 2_274     ┆           ┆           │
│           ┆           ┆           ┆ dca-fda3- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 48d…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 11        ┆           ┆ 8135921   ┆ NCF:e0a13 ┆   ┆          ┆ 2_274     ┆           ┆           │
│           ┆           ┆           ┆ 3e4-8a4a- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 4cf…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 11        ┆           ┆ 8135921   ┆ NCF:eff87 ┆   ┆          ┆ 2_274     ┆           ┆           │
│           ┆           ┆           ┆ 74a-e864- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 4c6…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 11        ┆           ┆ 8135921   ┆ NCF:c51e2 ┆   ┆          ┆ 2_510     ┆           ┆           │
│           ┆           ┆           ┆ 44d-abc4- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 426…      ┆   ┆          ┆           ┆           ┆           │
│ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ IDFM:TN:S ┆ … ┆ null     ┆ IDFM:shp_ ┆ 1         ┆ 0         │
│ 11        ┆           ┆ 8135921   ┆ NCF:4463d ┆   ┆          ┆ 2_510     ┆           ┆           │
│           ┆           ┆           ┆ 70e-a63d- ┆   ┆          ┆           ┆           ┆           │
│           ┆           ┆           ┆ 40b…      ┆   ┆          ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

## Trips stop times

In [8]:
# trip rer A
stop_times = pl.scan_csv("../ressources/stop_times.txt")
rer_trips_stop_times = (
    rer_trips.lazy()
    .select(["trip_id", "route_id", "route_long_name", "service_id"])
    .join(stop_times.lazy(),
          on="trip_id",
          how="inner")
    .sort("route_long_name")
)
rer_trips_stop_times.collect()

shape: (622_371, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ trip_id   ┆ route_id  ┆ route_lon ┆ service_i ┆ … ┆ stop_head ┆ timepoint ┆ pickup_bo ┆ drop_off │
│ ---       ┆ ---       ┆ g_name    ┆ d         ┆   ┆ sign      ┆ ---       ┆ oking_rul ┆ _booking │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ i64       ┆ e_id      ┆ _rule_id │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆           ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ IDFM:TN:S ┆ IDFM:C017 ┆ A         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:dee0d ┆ 42        ┆           ┆ 7973483   ┆   ┆           ┆           ┆           ┆          │
│ 87e-8a58- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4a0…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ IDFM:C017 ┆ A         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:dee0d ┆ 42        ┆           ┆ 7973483   ┆   ┆           ┆           ┆           ┆          │
│ 87e-8a58- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4a0…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ IDFM:C017 ┆ A         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:dee0d ┆ 42        ┆           ┆ 7973483   ┆   ┆           ┆           ┆           ┆          │
│ 87e-8a58- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4a0…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ IDFM:C017 ┆ A         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:dee0d ┆ 42        ┆           ┆ 7973483   ┆   ┆           ┆           ┆           ┆          │
│ 87e-8a58- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4a0…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ IDFM:C017 ┆ A         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:dee0d ┆ 42        ┆           ┆ 7973483   ┆   ┆           ┆           ┆           ┆          │
│ 87e-8a58- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4a0…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ IDFM:TN:S ┆ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:4463d ┆ 11        ┆           ┆ 8135921   ┆   ┆           ┆           ┆           ┆          │
│ 70e-a63d- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 40b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:4463d ┆ 11        ┆           ┆ 8135921   ┆   ┆           ┆           ┆           ┆          │
│ 70e-a63d- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 40b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:4463d ┆ 11        ┆           ┆ 8135921   ┆   ┆           ┆           ┆           ┆          │
│ 70e-a63d- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 40b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:4463d ┆ 11        ┆           ┆ 8135921   ┆   ┆           ┆           ┆           ┆          │
│ 70e-a63d- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 40b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IDFM:TN:S ┆ IDFM:C027 ┆ V         ┆ IDFM:TN:4 ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ NCF:4463d ┆ 11        ┆           ┆ 8135921   ┆   ┆           ┆           ┆           ┆          │
│ 70e-a63d- ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 40b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## RER Route by Parent_stop

In [9]:
rer_trips_stops = (
    rer_trips_stop_times.lazy()
    .group_by(["trip_id", "route_id", "route_long_name", "service_id"])
    .agg(pl.col("stop_id")
         .alias("stops"))
)
rer_trips_stops.collect()

shape: (40_853, 5)
┌──────────────────────┬─────────────┬─────────────────┬─────────────────────┬─────────────────────┐
│ trip_id              ┆ route_id    ┆ route_long_name ┆ service_id          ┆ stops               │
│ ---                  ┆ ---         ┆ ---             ┆ ---                 ┆ ---                 │
│ str                  ┆ str         ┆ str             ┆ str                 ┆ list[str]           │
╞══════════════════════╪═════════════╪═════════════════╪═════════════════════╪═════════════════════╡
│ IDFM:TN:SNCF:efcf14d ┆ IDFM:C01743 ┆ B               ┆ IDFM:TN:48040445    ┆ ["IDFM:monomodalSto │
│ 9-c97e-4e0…          ┆             ┆                 ┆                     ┆ pPlace:4733…        │
│ IDFM:TN:SNCF:4949b7b ┆ IDFM:C01737 ┆ H               ┆ IDFM:TN:48167488    ┆ ["IDFM:monomodalSto │
│ 9-c187-499…          ┆             ┆                 ┆                     ┆ pPlace:4789…        │
│ IDFM:TN:SNCF:22fdffd ┆ IDFM:C01742 ┆ A               ┆ IDFM:TN:48180525    ┆ ["IDFM:monomodalSto │
│ a-d3a9-4b2…          ┆             ┆                 ┆                     ┆ pPlace:4323…        │
│ IDFM:TN:SNCF:1c94711 ┆ IDFM:C01731 ┆ R               ┆ IDFM:TN:0391f943-2f ┆ ["IDFM:monomodalSto │
│ 4-c1da-460…          ┆             ┆                 ┆ d9-3b18-a81…        ┆ pPlace:4790…        │
│ IDFM:TN:SNCF:1cf9db8 ┆ IDFM:C01743 ┆ B               ┆ IDFM:TN:48040445    ┆ ["IDFM:monomodalSto │
│ 4-9e2d-4f2…          ┆             ┆                 ┆                     ┆ pPlace:4318…        │
│ …                    ┆ …           ┆ …               ┆ …                   ┆ …                   │
│ IDFM:TN:SNCF:471b99d ┆ IDFM:C01728 ┆ D               ┆ IDFM:TN:48167488    ┆ ["IDFM:monomodalSto │
│ d-b09d-44b…          ┆             ┆                 ┆                     ┆ pPlace:4790…        │
│ IDFM:TN:SNCF:54f0f92 ┆ IDFM:C01729 ┆ E               ┆ IDFM:TN:47973483    ┆ ["IDFM:monomodalSto │
│ 8-6c15-4b2…          ┆             ┆                 ┆                     ┆ pPlace:4870…        │
│ IDFM:TN:SNCF:90e2cb5 ┆ IDFM:C02711 ┆ V               ┆ IDFM:TN:48165673    ┆ ["IDFM:monomodalSto │
│ d-f32a-4e5…          ┆             ┆                 ┆                     ┆ pPlace:5877…        │
│ IDFM:TN:SNCF:9dbbc85 ┆ IDFM:C01736 ┆ N               ┆ IDFM:TN:48040445    ┆ ["IDFM:monomodalSto │
│ 3-1603-44b…          ┆             ┆                 ┆                     ┆ pPlace:4788…        │
│ IDFM:TN:SNCF:3ce2095 ┆ IDFM:C01739 ┆ J               ┆ IDFM:TN:48168307    ┆ ["IDFM:monomodalSto │
│ 6-1950-47b…          ┆             ┆                 ┆                     ┆ pPlace:5856…        │
└──────────────────────┴─────────────┴─────────────────┴─────────────────────┴─────────────────────┘

In [11]:
parent_stops_routes = (
    rer_trips_stops.lazy()
    .explode("stops", empty_as_null=True)
    .rename({"stops": "stop_id"})
    .join(
        stops.lazy()
        .select(["stop_id", "stop_name"]),
        on="stop_id",
        how="left"
    )
    .group_by(["stop_id", "stop_name"])
    .agg(
        pl.col("route_long_name")
        .unique()
        .alias("routes"),
        pl.col("route_id")
        .unique()
        .alias("routes_ids")
    )
    .sort("stop_name")
)

parent_stops_routes.collect()

shape: (547, 4)
┌────────────────────────────────┬───────────────────────┬───────────────────┬─────────────────┐
│ stop_id                        ┆ stop_name             ┆ routes            ┆ routes_ids      │
│ ---                            ┆ ---                   ┆ ---               ┆ ---             │
│ str                            ┆ str                   ┆ list[str]         ┆ list[str]       │
╞════════════════════════════════╪═══════════════════════╪═══════════════════╪═════════════════╡
│ IDFM:monomodalStopPlace:46387  ┆ Ablon                 ┆ ["C"]             ┆ ["IDFM:C01727"] │
│ IDFM:monomodalStopPlace:47915  ┆ Achères Grand Cormier ┆ ["A"]             ┆ ["IDFM:C01742"] │
│ IDFM:monomodalStopPlace:46647  ┆ Achères Ville         ┆ ["L", "A"]        ┆ ["IDFM:C01740", │
│                                ┆                       ┆                   ┆ "IDFM:C01742"]  │
│ IDFM:monomodalStopPlace:47916  ┆ Andrésy               ┆ ["J"]             ┆ ["IDFM:C01739"] │
│ IDFM:472379                    ┆ Angerville            ┆ ["TER Centre -    ┆ ["IDFM:C01857"] │
│                                ┆                       ┆ Val-de-Loire"]    ┆                 │
│ …                              ┆ …                     ┆ …                 ┆ …               │
│ IDFM:monomodalStopPlace:411455 ┆ Étigny - Véron        ┆ ["TER Bourgogne - ┆ ["IDFM:C01745"] │
│                                ┆                       ┆ Franche-Comt…     ┆                 │
│ IDFM:monomodalStopPlace:43081  ┆ Étréchy               ┆ ["C"]             ┆ ["IDFM:C01727"] │
│ IDFM:monomodalStopPlace:411365 ┆ Évreux Normandie      ┆ ["TER Normandie"] ┆ ["IDFM:C02375"] │
│ IDFM:monomodalStopPlace:47906  ┆ Évry - Courcouronnes  ┆ ["D"]             ┆ ["IDFM:C01728"] │
│ IDFM:monomodalStopPlace:45745  ┆ Évry - Val de Seine   ┆ ["D"]             ┆ ["IDFM:C01728"] │
└────────────────────────────────┴───────────────────────┴───────────────────┴─────────────────┘